### ISSUE TITLE
Decompressed Save File appears to be incomplete

### ISSUE THREAD

**Issue by gx570s** [topche-katt/hlsavetool#3] opened 2024-06-26 00:19 UTC
Hi Katt. Someone messaged me to say that when they decompressed their save file the result was incomplete. (It's missing things like the player name, player House etc). I'll attach the save file so you can try it for yourself. The tool did not report any errors. Could you investigate? Thanks!
[HL-01-00.zip](https://github.com/user-attachments/files/15980683/HL-01-00.zip)

**Comment by topche-katt** [comment] 2024-06-26 01:29
I couldn't reproduce the issue. Is there any chance we can get the `incomplete` file produced by the tool?

**Comment by gx570s** [comment] 2024-06-26 02:38
Sure. Here you go:
[HL-01-00.decomp.zip](https://github.com/user-attachments/files/15981626/HL-01-00.decomp.zip)

**Comment by topche-katt** [comment] 2024-06-26 07:38
Thank you @gx570s. The issue is not related to `hlsavetool`. I am closing this issue.

**Closed as completed by topche-katt** 2024-06-26 07:38 UTC
